const tests = require('../../../ui/src/handlers/module-specs');
const closeBrowser = require('../../../ui/src/handlers/other/closeBrowser');
const clearMemory = require('../../../ui/src/handlers/other/clearMemory');
const data = require('../../../ui/src/handlers/module-specs/data');
console.log = () => function () {};

data.addURV();
tests.workedJournalUi.other.calculateСurrentWorkedJournal();
tests.workedJournalUi.other.calculationDateWorkedJournal();
tests.workedJournalUi.other.checkCalculationWorkedJournal();
tests.workedJournalUi.other.printTableWorkedJournal();
tests.workedJournalUi.other.exportWorkedJournalXLSX();
tests.workedJournalUi.other.exportWorkedJournalCSV();
clearMemory();
tests.workedJournalUi.other.documentCalculationWorkedJournal();
tests.workedJournalUi.other.deleteCompositeDocumentWorkedJournal();
tests.workedJournalUi.other.staffDeptWorkedJournal();
tests.workedJournalUi.other.divisionFilterWorkedJournal();
tests.workedJournalUi.other.searchFilterWorkedJournal();
data.deleteURV();
clearMemory();