const Base = require('./base-page/base-page'), Auth = require('./auth-page/auth-page'),
    Rooms = require('./soft/administration/configuration-page/configuration-room-page'),
    Devices = require('./soft/administration/configuration-page/configuration-device-page'),
    License = require('./soft/administration/license-page/license-page'),
    AccessTemplate = require('./soft/pass-office/access-page/access-template-page'),
    AccessTemplateChange = require('./soft/pass-office/access-page/access-template-change-page'),
    DivisionPage = require('./soft/personal/division-page/division-page'),
    SchedulePage = require('./soft/personal/schedule-page/schedule-page'),
    SchedulePageChange = require('./soft/personal/schedule-page/schedule-change-page'),
    PositionPage = require('./soft/personal/positions-page/positions-page'),
    StaffPresentPage = require('./soft/personal/staff-page/staff-active-page'),
    StaffPageChange = require('./soft/personal/staff-page/staff-change-page'),
    StaffDimissed = require('./soft/personal/staff-page/staff-dimissed-page'),
    VisitorCurrentPage = require('./soft/pass-office/visitor-page/visitor-current-page'),
    VisitorOrderedPage = require('./soft/pass-office/visitor-page/visitor-ordered-page'),
    VisitorArchivedPage = require('./soft/pass-office/visitor-page/visitor-archive-page'),
    VisitorChangePage = require('./soft/pass-office/visitor-page/visitor-change-page'),
    StaffPassPage = require('./soft/pass-office/staff-pass-page/staff-pass-page'),
    StaffPassPageChange = require('./soft/pass-office/staff-pass-page/staff-pass-change-page'),
    AccessTemplateScheduleChangePage = require('./soft/pass-office/access-page/access-template-schedule-change-page'),
    AccessTemplateSchedulePage = require('./soft/pass-office/access-page/access-template-schedule-page'),
    AdditionalData = require('./soft/personal/additional-data-page/additional-data-page'),
    AccessTemplateScheduleHoliday = require('./soft/pass-office/access-page/access-template-schedule-holiday-page'),
    PremiseAccessAll = require('./soft/control-access/premise-access-page/premise-access-all-page'),
    PremiseAccessStaff = require('./soft/control-access/premise-access-page/premise-access-staff-page'),
    PremiseAccessVisitor = require('./soft/control-access/premise-access-page/premise-access-visitor-page'),
    VerificationJournal = require('./soft/control-access/verification-journal-page/verification-journal-page'),
    WhereAboutsAll = require('./soft/control-access/where-abouts-page/where-abouts-all-page'),
    WhereAboutsStaff = require('./soft/control-access/where-abouts-page/where-abouts-staff-page'),
    WhereAboutsVisitor = require('./soft/control-access/where-abouts-page/where-abouts-visitor-page'),
    PremisesAccessReportAll = require('./soft/control-access/premises-access-report-page/premises-access-report-all-page'),
    PremisesAccessReportStaff = require('./soft/control-access/premises-access-report-page/premises-access-report-staff-page'),
    PremisesAccessReportVisitor = require('./soft/control-access/premises-access-report-page/premises-access-report-visitor-page'),
    IdentifiersAll = require('./soft/control-access/identifiers-page/identifiers-all-page'),
    IdentifiersStaff = require('./soft/control-access/identifiers-page/identifiers-staff-page'),
    IdentifiersVisitor = require('./soft/control-access/identifiers-page/identifiers-visitor-page'),
    OrderpassOrder = require('./soft/orderpass/orderpass/orderpass-order-page'),
    OrderpassArchive = require('./soft/orderpass/orderpass/orderpass-archive-page'),
    OrderpassChange = require('./soft/orderpass/orderpass/orderpass-change-page'),
    WorkedJournal = require('./soft/urv/worked-journal-page/worked-journal-page');

module.exports = {
    //base
    base: new Base(),
    auth: new Auth(),

    //Персонал
    staffActive: new StaffPresentPage(),
    staffChange: new StaffPageChange(),
    staffDimissed: new StaffDimissed(),
    schedule: new SchedulePage(),
    schedulePageChange: new SchedulePageChange(),
    division: new DivisionPage(),
    position: new PositionPage(),
    additionalData: new AdditionalData(),

    //Бюро пропусков
    visitorOrdered: new VisitorOrderedPage(),
    visitorCurrent: new VisitorCurrentPage(),
    visitorArchive: new VisitorArchivedPage(),
    visitorChange: new VisitorChangePage(),
    staffPass: new StaffPassPage(),
    staffPassChange: new StaffPassPageChange(),
    accessTemplate: new AccessTemplate(),
    accessTemplateChange: new AccessTemplateChange(),
    accessTemplateSchedulePage: new AccessTemplateSchedulePage(),
    accessTemplateScheduleChangePage: new AccessTemplateScheduleChangePage(),
    accessTemplateScheduleHoliday: new AccessTemplateScheduleHoliday(),

    //УРВ
    workedJournal: new WorkedJournal(),

    //Контроль доступа
    premiseAccessAll: new PremiseAccessAll(),
    premiseAccessStaff: new PremiseAccessStaff(),
    premiseAccessVisitor: new PremiseAccessVisitor(),
    verificationJournal: new VerificationJournal(),
    whereAboutsAll: new WhereAboutsAll(),
    whereAboutsStaff: new WhereAboutsStaff(),
    whereAboutsVisitor: new WhereAboutsVisitor(),
    premisesAccessReportAll: new PremisesAccessReportAll(),
    premisesAccessReportStaff: new PremisesAccessReportStaff(),
    premisesAccessReportVisitor: new PremisesAccessReportVisitor(),
    identifiersAll: new IdentifiersAll(),
    identifiersStaff: new IdentifiersStaff(),
    identifiersVisitor: new IdentifiersVisitor(),

    //Заказ пропуска
    orderpassOrder: new OrderpassOrder(),
    orderpassArchive: new OrderpassArchive(),
    orderpassChange: new OrderpassChange(),

    //Администрирование
    room: new Rooms(),
    device: new Devices(),
    license: new License(),

}