const Base = require('./base-page/base-page'), Auth = require('./auth-page/auth-page'),
    Rooms = require('./soft/administration/configuration-page/configuration-room-page'),
    Devices = require('./soft/administration/configuration-page/configuration-device-page'),
    License = require('./soft/administration/license-page/license-page'),
    AccessTemplate = require('./soft/pass-office/access-page/access-template-page'),
    AccessTemplateChange = require('./soft/pass-office/access-page/access-template-change-page'),
    DivisionPage = require('./soft/personal/division-page/division-page'),
    SchedulePage = require('./soft/personal/schedule-page/schedule-page'),
    SchedulePageChange = require('./soft/personal/schedule-page/schedule-change-page'),
    PositionPage = require('./soft/personal/positions-page/positions-page'),
    StaffPresentPage = require('./soft/personal/staff-page/staff-active-page'),
    StaffPageChange = require('./soft/personal/staff-page/staff-change-page'),
    StaffDimissed = require('./soft/personal/staff-page/staff-dimissed-page'),
    VisitorCurrentPage = require('./soft/pass-office/visitor-page/visitor-current-page'),
    VisitorOrderedPage = require('./soft/pass-office/visitor-page/visitor-ordered-page'),
    VisitorArchivedPage = require('./soft/pass-office/visitor-page/visitor-archive-page'),
    VisitorChangePage = require('./soft/pass-office/visitor-page/visitor-change-page'),
    StaffPassPage = require('./soft/pass-office/staff-pass-page/staff-pass-page'),
    StaffPassPageChange = require('./soft/pass-office/staff-pass-page/staff-pass-change-page'),
    AccessTemplateScheduleChangePage = require('./soft/pass-office/access-page/access-template-schedule-change-page'),
    AccessTemplateSchedulePage = require('./soft/pass-office/access-page/access-template-schedule-page'),
    AdditionalData = require('./soft/personal/additional-data-page/additional-data-page'),
    AccessTemplateScheduleHoliday = require('./soft/pass-office/access-page/access-template-schedule-holiday-page'),
    PremiseAccessAll = require('./soft/control-access/premise-access-page/premise-access-all-page'),
    PremiseAccessStaff = require('./soft/control-access/premise-access-page/premise-access-staff-page'),
    PremiseAccessVisitor = require('./soft/control-access/premise-access-page/premise-access-visitor-page'),
    VerificationJournal = require('./soft/control-access/verification-journal-page/verification-journal-page'),
    WhereAboutsAll = require('./soft/control-access/where-abouts-page/where-abouts-all-page'),
    WhereAboutsStaff = require('./soft/control-access/where-abouts-page/where-abouts-staff-page'),
    WhereAboutsVisitor = require('./soft/control-access/where-abouts-page/where-abouts-visitor-page'),
    PremisesAccessReportAll = require('./soft/control-access/premises-access-report-page/premises-access-report-all-page'),
    PremisesAccessReportStaff = require('./soft/control-access/premises-access-report-page/premises-access-report-staff-page'),
    PremisesAccessReportVisitor = require('./soft/control-access/premises-access-report-page/premises-access-report-visitor-page'),
    IdentifiersAll = require('./soft/control-access/identifiers-page/identifiers-all-page'),
    IdentifiersStaff = require('./soft/control-access/identifiers-page/identifiers-staff-page'),
    IdentifiersVisitor = require('./soft/control-access/identifiers-page/identifiers-visitor-page'),
    OrderpassOrder = require('./soft/orderpass/orderpass/orderpass-order-page'),
    OrderpassArchive = require('./soft/orderpass/orderpass/orderpass-archive-page'),
    OrderpassChange = require('./soft/orderpass/orderpass/orderpass-change-page'),
    WorkedJournal = require('./soft/urv/worked-journal-page/worked-journal-page'),
    Timesheet = require('./soft/urv/timesheet-page/timesheet-page'),
    Reports = require('./soft/urv/reports-page/reports-page'),
    Violator = require('./soft/urv/discipline-reports-page/violators-page'),
    Presence = require('./soft/urv/discipline-reports-page/presences-page'),
    Absent = require('./soft/urv/discipline-reports-page/absents-page'),
    Late = require('./soft/urv/discipline-reports-page/lates-page'),
    Early = require('./soft/urv/discipline-reports-page/earlys-page'),
    Overwork = require('./soft/urv/discipline-reports-page/overworks-page'),
    TimePresence = require('./soft/urv/time-presence-page/time-presence-page'),
    Supporting = require('./soft/urv/support-page/supporting-page'),
    PaidOvertime = require('./soft/urv/support-page/paid-overtime-page'),
    DocumentJustificationPage = require('./soft/urv/document-page/document-justification-page'),
    DocumentOvertimePage = require('./soft/urv/document-page/document-overtime-page'),
    DocumentExplanatoryPage = require('./soft/urv/document-page/document-explanatory-page'),
    AccessTemplateComissionPage = require('./soft/pass-office/access-page/access-template-comission-page'),
    DesignPage = require('./soft/pass-office/design-page/design-page'),
    DesignChangePage = require('./soft/pass-office/design-page/design-change-page'),
    VisitorReportPage = require('./soft/pass-office/visitor-report-page/visitor-report-page'),
    HolidayPage = require('./soft/personal/holiday-page/holiday-page'),
    EventRenamePage = require('./soft/administration/configuration-page/configuration-event-page'),
    TemplateCameraPage = require('./soft/administration/configuration-page/configuration-camera-page'),
    SystemPage = require('./soft/administration/configuration-page/configuration-system-page'),
    EventPage = require('./soft/administration/event-page/event-page'),
    EventactionPage = require('./soft/administration/eventaction-page/eventaction-page'),
    EventactionChangePage = require('./soft/administration/eventaction-page/eventaction-change-page'),
    TaskPage = require('./soft/administration/task/task-page'),
    TaskChangePage = require('./soft/administration/task/task-change-page'),
    OperatorPage = require('./soft/administration/operator-page/operator-page'),
    OperatorChangePage = require('./soft/administration/operator-page/operator-change-page'),
    RolePage = require('./soft/administration/role-page/role-page'),
    RoleChangePage  = require('./soft/administration/role-page/role-change-page'),
    VerificationPage = require('./soft/verification/verification/verification-page'),
    VerificationConfigPage = require('./soft/verification/verification-config/verification-config-page'),
    VerificationConfigChangePage = require('./soft/verification/verification-config/verification-config-change-page'),
    PlanPage = require('./soft/monitoring/plan/plan-page');


module.exports = {
    //base
    base: new Base(),
    auth: new Auth(),

    //Персонал
    staffActive: new StaffPresentPage(),
    staffChange: new StaffPageChange(),
    staffDimissed: new StaffDimissed(),
    schedule: new SchedulePage(),
    schedulePageChange: new SchedulePageChange(),
    division: new DivisionPage(),
    position: new PositionPage(),
    additionalData: new AdditionalData(),
    holiday: new HolidayPage(),

    //Бюро пропусков
    visitorOrdered: new VisitorOrderedPage(),
    visitorCurrent: new VisitorCurrentPage(),
    visitorArchive: new VisitorArchivedPage(),
    visitorChange: new VisitorChangePage(),
    staffPass: new StaffPassPage(),
    staffPassChange: new StaffPassPageChange(),
    accessTemplate: new AccessTemplate(),
    accessTemplateChange: new AccessTemplateChange(),
    accessTemplateSchedulePage: new AccessTemplateSchedulePage(),
    accessTemplateScheduleChangePage: new AccessTemplateScheduleChangePage(),
    accessTemplateScheduleHoliday: new AccessTemplateScheduleHoliday(),
    accessTemplateComission: new AccessTemplateComissionPage(),
    design: new DesignPage(),
    designChange: new DesignChangePage(),
    visitorReport: new VisitorReportPage(),

    //УРВ
    workedJournal: new WorkedJournal(),
    timesheet: new Timesheet(),
    reports: new Reports(),
    violator: new Violator(),
    presence: new Presence(),
    absent: new Absent(),
    late: new Late(),
    early: new Early(),
    overwork: new Overwork(),
    timePresence: new TimePresence(),
    supporting: new Supporting(),
    paidOvertime: new PaidOvertime(),
    documentJustification: new DocumentJustificationPage(),
    documentOvertime: new DocumentOvertimePage(),
    documentExplanatory: new DocumentExplanatoryPage(),

    //Контроль доступа
    premiseAccessAll: new PremiseAccessAll(),
    premiseAccessStaff: new PremiseAccessStaff(),
    premiseAccessVisitor: new PremiseAccessVisitor(),
    verificationJournal: new VerificationJournal(),
    whereAboutsAll: new WhereAboutsAll(),
    whereAboutsStaff: new WhereAboutsStaff(),
    whereAboutsVisitor: new WhereAboutsVisitor(),
    premisesAccessReportAll: new PremisesAccessReportAll(),
    premisesAccessReportStaff: new PremisesAccessReportStaff(),
    premisesAccessReportVisitor: new PremisesAccessReportVisitor(),
    identifiersAll: new IdentifiersAll(),
    identifiersStaff: new IdentifiersStaff(),
    identifiersVisitor: new IdentifiersVisitor(),

    // Верификация
    verify: new VerificationPage(),
    verifyConfig: new VerificationConfigPage(),
    verifyConfigChange: new VerificationConfigChangePage(),

    //Заказ пропуска
    orderpassOrder: new OrderpassOrder(),
    orderpassArchive: new OrderpassArchive(),
    orderpassChange: new OrderpassChange(),

    // Мониторинг
    plan: new PlanPage(),

    //Администрирование
    room: new Rooms(),
    device: new Devices(),
    eventRename: new EventRenamePage(),
    camera: new TemplateCameraPage(),
    system: new SystemPage(),
    event: new EventPage(),
    eventaction: new EventactionPage(),
    eventactionChange: new EventactionChangePage(),
    task: new TaskPage(),
    taskChange: new TaskChangePage(),
    operator:  new OperatorPage(),
    operatorChange: new OperatorChangePage(),
    role: new RolePage(),
    roleChange: new RoleChangePage(),
    license: new License(),

}